### ISSUE TITLE
Add example(s)

### ISSUE THREAD

**Issue by JayKickliter** [octobuild/daemon-rs#12]
This is the first crate that popped up when I searched 'daemon' on crates.io. After pulling up the docs, I have no idea of how to use this crate. Considering that this is a desireable crate name, please, please, add documentation or transfer ownership of the crate to someone else who has more time to spend on it.

**Comment by wizebin** [comment]
https://github.com/bozaro/daemon-rs/blob/master/src/bin/example.rs

There's a sample here
