### ISSUE TITLE
Bundling a service with an installer on Windows?

### ISSUE THREAD

**Issue by emou** [octobuild/daemon-rs#4]
@bozaro have you built a windows service complete with an installer?
How would you go around doing that?

**Comment by emou** [comment]
Nevermind, I guess using `wix` and pointing to the executable produced with this library should work as it uses the Windows service API. Thanks for publishing this code!

**Comment by bozaro** [comment]
I'm sorry for delay.
I can recommend https://wixsharp.codeplex.com/ as good wix wrapper to create installers.
